### ISSUE TITLE
Migration to 13.0

### ISSUE THREAD

**Issue by theangryangel** [GlodoUK/web#5]
- [x] concurrency_warning
- [ ] web_button_enable_with_no_record 
- [ ] web_higher_upload_limit
- [ ] web_many2many_list

**Comment by mattl5543** [comment]
Updated concurrency_warning to work with 13.0

In 13.0 the page will automatically reload (without killing user's ongoing edits) as per an issue in our helpdesk module. 

I've also removed the base.automation records, so that they can be added/configured in specific projects.
